- name: Upgrade packages
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 300
  become: yes

- name: Install packages
  apt:
    name:
      - aptitude
      - jq
      - curl
      - git-core
      - at
      - ufw
      - ghostscript
      - imagemagick
      - openssl
    state: present
    update_cache: yes
