---
- name: Download WordPress
  get_url:
    url: "https://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: Create WordPress directory
  file:
    path: "{{ wp_install_dir }}"
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'

- name: Extract WordPress
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "{{ wp_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: nginx
    group: nginx

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ wp_install_dir }}/wp-config.php"
    owner: nginx
    group: nginx

- name: Configure Nginx
  template:
    src: nginx-wordpress.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf
  notify: Reload Nginx

- name: Generate dhparams file
  openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 2048
    owner: nginx
    group:  nginx
    mode: '0644'
  notify: Reload Nginx
