---
- name: Ensure required packages are installed
  apt:
    name:
      - python3
      - python3-pip
      - rsyslog 
      - python3-requests
      - python3-dotenv
    state: present

- name: Ensure script directory exists
  file:
    path: "{{ script_dir }}"
    state: directory
    mode: '0755'

- name: Copy .env file
  ansible.builtin.copy:
    src: '.env'
    dest: '{{ script_dir }}'
    owner: matias
    group: matias
    mode: '0644'

- name: Setup cron job
  cron:
    name: "Update Cloudflare DDNS"
    minute: "0"
    job: "/usr/bin/python3 {{ script_dir }}/{{ script_name }}"
    cron_file: "{{ cron_identifier }}"
    user: matias

- name: Configure rsyslog for cron
  copy:
    content: |
      cron.*    /var/log/cron.log
    dest: /etc/rsyslog.d/50-cron.conf
  notify: 
    - Restart cron
    - Restart rsyslog

- name: Ensure cron log file exists with proper permissions
  file:
    path: /var/log/cron.log
    state: touch
    mode: '0644'
    owner: root
    group: adm

